// const faker = require('faker');

// const createFakeData = () => ({
//   first_name: faker.name.firstName(),
//   last_name : faker.name.lastName(),
//   dob       : faker.date.past(),
//   parent_id : Math.floor(Math.random() * (10 - 1)) + 1,
//   gender    : Math.floor(Math.random() * (2 - 1)) + 1,
//   address   : faker.address.streetAddress(),
//   contact_no: faker.phone.phoneNumber(),
//   email     : faker.internet.email(),
//   password  : faker.internet.password(),
//   avatar    : faker.image.avatar(),
//   year      : 2020,
//   school_id : 1,
// });

exports.seed = function (knex) {

  // const fakeData = [];
  // const desiredFakeData = 10;

  // for (let index = 0; index < desiredFakeData; index++) {
  //   fakeData.push(createFakeData());

  // }
  return knex('students').insert([
    {
      "id"         : 1,
      "first_name" : "Dasia",
      "last_name"  : "Bernier",
      "email"      : "Ramiro.Fisher@gmail.com",
      "password"   : "1J5oFPBfhot4eEn",
      "dob"        : 1559351145692,
      "parent_id"  : 9,
      "gender"     : 1,
      "address"    : "69701 McLaughlin Viaduct",
      "contact_no" : "706-866-5118",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/iduuck\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    },
    {
      "id"         : 2,
      "first_name" : "Jarret",
      "last_name"  : "Boyer",
      "email"      : "Jaquelin.Conroy@hotmail.com",
      "password"   : "9heEEkLZVWJfTsp",
      "dob"        : 1577031410686,
      "parent_id"  : 1,
      "gender"     : 1,
      "address"    : "65074 Alta Brooks",
      "contact_no" : "(609) 420-0111",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/nitinhayaran\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    },
    {
      "id"         : 3,
      "first_name" : "Loyce",
      "last_name"  : "Quitzon",
      "email"      : "Alba42@hotmail.com",
      "password"   : "hbKSaZw54MFR4LH",
      "dob"        : 1584758066220,
      "parent_id"  : 9,
      "gender"     : 1,
      "address"    : "577 Wilkinson Highway",
      "contact_no" : "(118) 069-6780 x8130",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/amanruzaini\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    },
    {
      "id"         : 4,
      "first_name" : "Kaitlin",
      "last_name"  : "Boyer",
      "email"      : "Kylee52@gmail.com",
      "password"   : "74sdcvktmemfxlg",
      "dob"        : 1568201200643,
      "parent_id"  : 8,
      "gender"     : 1,
      "address"    : "198 Tianna Dale",
      "contact_no" : "(306) 149-8614",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/rez___a\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    },
    {
      "id"         : 5,
      "first_name" : "Nona",
      "last_name"  : "Braun",
      "email"      : "Jayme.Flatley77@yahoo.com",
      "password"   : "TUwY1o2mtT7r2XL",
      "dob"        : 1563150554399,
      "parent_id"  : 8,
      "gender"     : 1,
      "address"    : "7820 Joaquin View",
      "contact_no" : "(905) 191-9579",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/shalt0ni\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    },
    {
      "id"         : 6,
      "first_name" : "Hector",
      "last_name"  : "Morissette",
      "email"      : "Helga_Cummerata@gmail.com",
      "password"   : "glFUXS1jJdKldP7",
      "dob"        : 1568532803985,
      "parent_id"  : 9,
      "gender"     : 1,
      "address"    : "192 Jakob Estates",
      "contact_no" : "330-454-3072",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/steynviljoen\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    },
    {
      "id"         : 7,
      "first_name" : "Darlene",
      "last_name"  : "MacGyver",
      "email"      : "Erich13@yahoo.com",
      "password"   : "UdaO7IKT_boUlka",
      "dob"        : 1574880861644,
      "parent_id"  : 7,
      "gender"     : 1,
      "address"    : "5371 Hansen Station",
      "contact_no" : "1-996-035-1241",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/al_li\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    },
    {
      "id"         : 8,
      "first_name" : "Eleanora",
      "last_name"  : "Kessler",
      "email"      : "Lambert9@yahoo.com",
      "password"   : "4LSURmAzThMFv3t",
      "dob"        : 1566971806069,
      "parent_id"  : 7,
      "gender"     : 1,
      "address"    : "11529 Ortiz Tunnel",
      "contact_no" : "797.997.0518 x501",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/alek_djuric\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    },
    {
      "id"         : 9,
      "first_name" : "Keith",
      "last_name"  : "Huel",
      "email"      : "Molly.Gulgowski97@gmail.com",
      "password"   : "gMAZUHfBbr22Gnh",
      "dob"        : 1566754120485,
      "parent_id"  : 2,
      "gender"     : 1,
      "address"    : "16785 Kassulke Bypass",
      "contact_no" : "676.534.8890 x964",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/besbujupi\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    },
    {
      "id"         : 10,
      "first_name" : "Lorenzo",
      "last_name"  : "Lind",
      "email"      : "Jaida.Schuster@gmail.com",
      "password"   : "m9jaPlKJQAcPh1Y",
      "dob"        : 1578732544638,
      "parent_id"  : 5,
      "gender"     : 1,
      "address"    : "0998 Sylvan Greens",
      "contact_no" : "(433) 963-1889 x52568",
      "avatar"     : "https:\/\/s3.amazonaws.com\/uifaces\/faces\/twitter\/dshster\/128.jpg",
      "created_at" : "2020-05-18 18:25:33",
      "modified_at": null,
      "deleted_at" : null,
      "is_deleted" : 0,
      "year"       : 2020,
      "school_id"  : 1
    }
  ]
  );
};

